"""add provider_unit_count and system_unit_count metric types

Revision ID: 92bd2a56238f
Revises: ed0dd59f436b
Create Date: 2025-08-14 07:53:51.580673

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92bd2a56238f"
down_revision: str | None = "ed0dd59f436b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the old constraint
    op.drop_constraint("valid_metric_type", "statistics", type_="check")

    # Add the new constraint with additional metric types
    op.create_check_constraint(
        "valid_metric_type",
        "statistics",
        "metric_type IN ('dataset_count', 'dataset_registration_rate', 'dataset_modification_rate', "
        "'dataset_unit_count', 'provider_count', 'provider_dataset_count', 'provider_activity_score', "
        "'provider_unit_count', 'validation_success_rate', 'validation_error_rate', 'validation_processing_time', "
        "'validation_job_count', 'abcd_compliance_rate', 'xml_archive_count', 'citation_completeness', "
        "'geographic_coverage', 'system_storage_size', 'system_processing_load', 'system_api_response_time', "
        "'system_unit_count')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the new constraint
    op.drop_constraint("valid_metric_type", "statistics", type_="check")

    # Restore the old constraint without new metric types
    op.create_check_constraint(
        "valid_metric_type",
        "statistics",
        "metric_type IN ('dataset_count', 'dataset_registration_rate', 'dataset_modification_rate', "
        "'dataset_unit_count', 'provider_count', 'provider_dataset_count', 'provider_activity_score', "
        "'validation_success_rate', 'validation_error_rate', 'validation_processing_time', "
        "'validation_job_count', 'abcd_compliance_rate', 'xml_archive_count', 'citation_completeness', "
        "'geographic_coverage', 'system_storage_size', 'system_processing_load', 'system_api_response_time')",
    )
    # ### end Alembic commands ###
