"""Add failed_tasks durable dead-letter sink

Implements the durable, redrivable dead-letter store behind RH-07 /
REQ-CEL-2 / F-CELERY-02. The previous "DLQ" was a phantom
``task_dead_letter_queue_config`` key (inert) plus a ``logger.critical`` after
which the message was acked and the payload dropped. ``LoggingTask.on_failure``
now persists ``{task_id, task_name, args, kwargs, last exception, timestamp}`` to
this table on a task's FINAL failure / give-up path, and ``task_base.redrive``
re-submits a stored payload.

Hand-written (not autogenerated) per docs/DATABASE_MIGRATION_GUIDE.md; chains off
the RH-06 unique-index migration (the current head).

Revision ID: b7e2c9a4f013
Revises: c4f1a2b9d7e3
Create Date: 2026-06-26 12:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7e2c9a4f013"
down_revision: str | None = "c4f1a2b9d7e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "failed_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=True),
        sa.Column("task_name", sa.String(), nullable=False),
        sa.Column("args", sa.Text(), nullable=True),
        sa.Column("kwargs", sa.Text(), nullable=True),
        sa.Column("exception", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_failed_tasks_id", "failed_tasks", ["id"], unique=False)
    op.create_index("ix_failed_tasks_task_id", "failed_tasks", ["task_id"], unique=False)
    op.create_index("ix_failed_tasks_task_name", "failed_tasks", ["task_name"], unique=False)


def downgrade() -> None:
    op.drop_index("ix_failed_tasks_task_name", table_name="failed_tasks")
    op.drop_index("ix_failed_tasks_task_id", table_name="failed_tasks")
    op.drop_index("ix_failed_tasks_id", table_name="failed_tasks")
    op.drop_table("failed_tasks")
