"""Add dacenter boolean flag designating official data centers

Revision ID: d03846f7cbdf
Revises: f8716259908d
Create Date: 2025-04-29 05:40:52.463542

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d03846f7cbdf"
down_revision: str | None = "f8716259908d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("data_providers", sa.Column("isDataCenter", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_providers", "isDataCenter")
    # ### end Alembic commands ###
