"""Add statistics table

Revision ID: ed0dd59f436b
Revises: d03846f7cbdf
Create Date: 2025-08-12 07:06:04.061980

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ed0dd59f436b"
down_revision: str | None = "d03846f7cbdf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("metric_type", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("period", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(entity_type = 'system' AND entity_id IS NULL) OR (entity_type != 'system' AND entity_id IS NOT NULL)",
            name="entity_id_consistency",
        ),
        sa.CheckConstraint(
            "entity_type IN ('system', 'provider', 'dataset', 'datacenter')",
            name="valid_entity_type",
        ),
        sa.CheckConstraint(
            "metric_type IN ('dataset_count', 'dataset_registration_rate', 'dataset_modification_rate', 'dataset_unit_count', 'provider_count', 'provider_dataset_count', 'provider_activity_score', 'validation_success_rate', 'validation_error_rate', 'validation_processing_time', 'validation_job_count', 'abcd_compliance_rate', 'xml_archive_count', 'citation_completeness', 'geographic_coverage', 'system_storage_size', 'system_processing_load', 'system_api_response_time')",
            name="valid_metric_type",
        ),
        sa.CheckConstraint(
            "period IN ('daily', 'weekly', 'monthly', 'quarterly', 'yearly')", name="valid_period"
        ),
        sa.CheckConstraint("value >= 0", name="non_negative_value"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_statistics_date", "statistics", ["date"], unique=False)
    op.create_index(
        "idx_statistics_entity", "statistics", ["entity_type", "entity_id", "date"], unique=False
    )
    op.create_index(
        "idx_statistics_lookup",
        "statistics",
        ["metric_type", "entity_type", "entity_id", "period"],
        unique=False,
    )
    op.create_index(
        "idx_statistics_metric", "statistics", ["metric_type", "period", "date"], unique=False
    )
    op.create_index(op.f("ix_statistics_id"), "statistics", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_statistics_id"), table_name="statistics")
    op.drop_index("idx_statistics_metric", table_name="statistics")
    op.drop_index("idx_statistics_lookup", table_name="statistics")
    op.drop_index("idx_statistics_entity", table_name="statistics")
    op.drop_index("idx_statistics_date", table_name="statistics")
    op.drop_table("statistics")
    # ### end Alembic commands ###
