"""add unique constraint for statistics to prevent duplicates

Revision ID: eeee34d2629a
Revises: 5170fba784be
Create Date: 2025-08-14 10:17:37.692700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeee34d2629a'
down_revision: Union[str, None] = '5170fba784be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add unique constraint to prevent duplicate statistics entries for the same metric/entity/period/date combination
    op.create_unique_constraint(
        'uq_statistics_unique_entry', 
        'statistics', 
        ['metric_type', 'entity_type', 'entity_id', 'period', 'date']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove unique constraint
    op.drop_constraint('uq_statistics_unique_entry', 'statistics', type_='unique')
    # ### end Alembic commands ###
