"""Add validation job model

Revision ID: f8716259908d
Revises: add_timestamp_fields
Create Date: 2025-03-21 08:02:38.882750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8716259908d'
down_revision: Union[str, None] = '84a53b5a2b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('validation_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archive_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('valid_files', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('validation_time', sa.Float(), nullable=True),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['archive_id'], ['xml_archives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index('idx_dataset_provider', 'datasets', ['provider_id'], unique=False)
    op.create_index('idx_useful_link_dataset', 'useful_links', ['dataset_id'], unique=False)
    op.create_index('idx_xml_archive_dataset', 'xml_archives', ['dataset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_xml_archive_dataset', table_name='xml_archives')
    op.drop_index('idx_useful_link_dataset', table_name='useful_links')
    op.drop_index('idx_dataset_provider', table_name='datasets')
    op.drop_table('validation_jobs')
    # ### end Alembic commands ###
